# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Florian MORGAN
email: florian.morgan@gmail.com
description: > # Description:
  Here you will find my resume (CV)
  It is made for french language and french people, however, english speakers
  could understand it also.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://superbob.github.io/cv" # the base hostname & protocol for your site
github_username:  superbob

# Build settings
markdown: kramdown
exclude: [render-pdf.js]
